services:
  app:
    image: ${APP_IMAGE}
    container_name: when2go-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PWD: ${DB_PWD}
    depends_on:
      when2go-redis:
        condition: service_healthy
    networks:
      - when2go-net
    restart: unless-stopped

  when2go-redis:
    image: redis:7-alpine
    container_name: when2go-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - when2go-net

networks:
  when2go-net:
    driver: bridge

volumes:
  redis-data:
