spring:
  profiles:
    active: dev

google:
  routes:
    api-key: ${GOOGLE_ROUTES_API_KEY:}
    base-url: ${GOOGLE_ROUTES_BASE_URL:https://routes.googleapis.com}

trip:
  recalc:
    enabled: ${TRIP_RECALC_ENABLED:false}

gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyCsn2hAU0XNuzGBRng_ZsGw6q_vZLIxrGM}
  base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
  model: ${GEMINI_MODEL:gemini-2.5-flash}
