apiVersion: 1

datasources:
  - name: CloudWatch
    uid: cloudwatch-when2go
    type: cloudwatch
    access: proxy
    isDefault: true
    jsonData:
      authType: keys
      defaultRegion: ap-northeast-2
    secureJsonData:
      accessKey: ${GF_AWS_ACCESS_KEY_ID}
      secretKey: ${GF_AWS_SECRET_ACCESS_KEY}
    editable: false
